[package]
name = "current-batch"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
current-zset.workspace = true
current-plan.workspace = true
current-ops.workspace = true
current-state.workspace = true
current-circuit.workspace = true
current-sql.workspace = true
current-memo.workspace = true
current-log.workspace = true
arrow-array.workspace = true
arrow-schema.workspace = true
parquet.workspace = true
thiserror.workspace = true

[dev-dependencies]
current-oracle.workspace = true

[lints]
workspace = true
